title: M27 Code
author: Minater247
email: nreed132@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An amateur high-school coder that makes things that sometimes work.
  Progress reports, features, and other things can be found on this
  blog!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
